# Copyright (c) 2025 Bayrem Gharsellaoui
# SPDX-License-Identifier: Apache-2.0

name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [native_sim, nucleo_f767zi]

    steps:
      - name: Checkout module repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Set up Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          manifest-file-name: west.yml
          toolchains: arm-zephyr-eabi

      - name: Build on ${{ matrix.board }}
        run: |
          west build -b ${{ matrix.board }} samples/drivers/pn532
